name: Json Rest Server

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.2.3'
      
      - name: Get Dependencies
        run: dart pub get

      - name: Run Tests
        run: dart test --concurrency=1
